vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.cmdheight = 0 -- hide command bar when inactive
vim.opt.signcolumn = "yes"
vim.opt.shortmess = { o = true }
vim.wo.number = true -- Show line numbers
vim.o.relativenumber = true -- Set relative numbered lines
vim.o.clipboard = "unnamedplus" -- Sync clipboard between OS and Neovim
vim.o.wrap = false -- Display lines as one long line
vim.o.linebreak = true -- Don't split words
vim.o.mouse = "a" -- Enable mouse mode
vim.o.autoindent = true -- Copy indent from current line when starting a new one
vim.o.ignorecase = true -- Case-insensitive searching UNLESS \C or capital in search
vim.o.smartcase = true -- Smart case
vim.o.shiftwidth = 4 -- The number of spaces inserted for each indentation
vim.o.tabstop = 4 -- Insert n spaces for a tab
vim.o.softtabstop = 999 -- Number of spaces that a tab counts for while performing editing operations
vim.o.expandtab = true -- Convert tabs to spaces
vim.o.scrolloff = 4 -- Minimal number of screen lines to keep above and below the cursor
vim.o.sidescrolloff = 8 -- Minimal number of screen columns either side of cursor if wrap is `false`
vim.o.cursorline = false -- Highlight the current line
vim.o.splitbelow = true -- Force all horizontal splits to go below current window
vim.o.splitright = true -- Force all vertical splits to go to the right of current window
vim.o.hlsearch = false -- Set highlight on search
vim.o.showmode = false -- Hide mode like -- INSERT --
vim.opt.termguicolors = true -- Set termguicolors to enable highlight groups
vim.o.numberwidth = 4 -- Set number column width to 4
vim.o.smartindent = true -- Make indenting smarter
vim.o.pumheight = 10 -- Pop up menu height
vim.o.cmdheight = 1 -- More space in the Neovim command line for displaying messages
vim.o.updatetime = 2000 -- Decrease update time (default: 4000)
vim.o.undofile = true -- Save undo history
vim.o.completeopt = "menuone,noselect" -- Set completeopt to have a better completion experience
vim.opt.virtualedit = "block"
